# Generated by Django 3.1 on 2021-06-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
