# Generated by Django 3.1 on 2021-06-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210613_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
