# Generated by Django 3.1 on 2021-06-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210613_1900'),
        ('inventory', '0003_auto_20210613_1900'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_book', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_book', to='member.members'),
        ),
    ]
